#!/bin/bash
# This is config file for dot.
# If you want to know all the description, see README.
#==============================================================================
# General Settings                                                          {{{
#==============================================================================

# You can change the dotfiles to clone
clone_repository='https://github.com/username/dotfiles.git'

# Set the directory that the script regard as dotfiles directory.
#dotdir="$HOME/.dotfiles"

# Set the path to your dotlink which describes the correspondence relation.
#dotlink="$dotdir/dotlink"
#linkfiles=("${dotlink}")

# If you want to load additional local setting, add its path to $linkfiles.
# (But it doesn't affect to `dot edit` and `dot add` command, so you should
# edit these files manually.)
#dotlinklocal="$HOME/.config/dot/dotlink.local"
#linkfiles=("${dotlink}" "${dotlinklocal}")

# You can switch the dotlinklocal by its OS type like below:

# (In zsh)

#case ${OSTYPE} in
#    *linux*)
#        dotlinklocal="${dotdir}/dotlink.linux"
#        ;;
#    *darwin*)
#        dotlinklocal="${dotdir}/dotlink.mac"
#        ;;
#    *cygwin*|*msys*)
#        dotlinklocal="${dotdir}/dotlink.windows"
#        ;;
#esac
#linkfiles=("${dotlink}" "${dotlinklocal}")

# (In bash)

#if [ "$(uname)" == 'Darwin' ]; then
#  dotlinklocal="${dotdir}/dotlink.linux"
#elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
#  dotlinklocal="${dotdir}/dotlink.mac"
#elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]; then
#  dotlinklocal="${dotdir}/dotlink.windows"
#fi
#linkfiles=("${dotlink}" "${dotlinklocal}")

#===========================================================================}}}
# Options                                                                   {{{
#==============================================================================

# "dot" uses "shallow clone".
# You can clone the only latest commit of the project if set to true.
#dotclone_shallow=false

# You can choose the action interactively if the file to link is already exist.
# If you set it false, just show message but do nothing (provided option -i).
#dotset_interactive=true

# Toggle the verbosity for output of `dot set` (option -v).
#dotset_verbose=false

# You can update submodule in your repository if you set the option below true.
#dotpull_update_submodule=true

# You can choose diff command as you want.
#diffcmd="colordiff -u"

# Command to edit two files with diff highlights.
#edit2filecmd='vimdiff'

# Set your favorite editor.
# (setting priority: this option > $EDITOR (default) > xdg-open)
#dot_edit_default_editor='vim +'

#===========================================================================}}}
# Load other config file                                                    {{{
#==============================================================================
# If you want to load a machine specific configuration, source that file here.
# `dotbundle file` source the file if it exists.

#dotbundle "$HOME/.config/dot/dotrc.local"

#===========================================================================}}}
